/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\ZACH\Documents\mingw64\bin\gcc.exe -c  -w  -IC:\Users\ZACH\Documents\nim-0.17.0\lib -o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\client.o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\client.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <windows.h>
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct GcThread_hgJQSlfXDOK3SwSHjeZBXg GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct SharedList_9cWkTIPQvNw7gFHMOEzMCLw SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct FlowVarObj_a5vp0WwZohkMPdG8GkZciw FlowVarObj_a5vp0WwZohkMPdG8GkZciw;
typedef struct Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ;
typedef struct FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg;
typedef struct TNimObject TNimObject;
typedef struct Semaphore_sx9abLHOwgGDBH9bpoqw2ezw Semaphore_sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct Exception Exception;
typedef struct TY_WF89a8QyKeDCh4DYWTmSiBg TY_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TSafePoint TSafePoint;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
typedef NF TY_SBX73RxxTewX4sqVYGfdEA[1001];
struct  GcThread_hgJQSlfXDOK3SwSHjeZBXg  {
TY_SBX73RxxTewX4sqVYGfdEA tls;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  SharedList_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
CRITICAL_SECTION lock;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
};
struct  Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ  {
FILE* f0;
FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv1;
};
typedef N_NIMCALL_PTR(void, TY_fhqfcnDhIcLpBpSTVsWEZg) (void* thread, void* args);
struct  TNimObject  {
TNimType* m_type;
};
struct  Semaphore_sx9abLHOwgGDBH9bpoqw2ezw  {
NI c;
CRITICAL_SECTION L;
NI counter;
};
struct  FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg  {
  TNimObject Sup;
NIM_BOOL ready;
NIM_BOOL usesSemaphore;
NIM_BOOL awaited;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA* ai;
NI idx;
void* data;
void* owner;
};
struct  FlowVarObj_a5vp0WwZohkMPdG8GkZciw  {
  FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg Sup;
NimStringDesc* blob;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* TY_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct  SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw  {
SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
TY_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct  AwaitInfo_InuzBj4ASNnb8C8ZpRzfbA  {
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI idx;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(NIM_BOOL, TY_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} TY_IIomJ6ptE6vfJ5zRbATgkQ;
struct TY_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  TY_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
typedef struct {TY_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
TY_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_LLyFo9bsdu1ZXMDvAe8DhrQ;
TY_sM4lkSb7zS6F7OVMvW9cffQ* environment_mlhK49b6YMgc9cgrcYkKq9a3g;
TY_sM4lkSb7zS6F7OVMvW9cffQ* ownArgv_WVJ54JSHy7VxacV39bwBPFA;
NIM_BOOL isSlave_t9a8wsVVRYqGEKhg1vb49b3g;
} NimThreadVars;
N_NIMCALL(NI, nosparamCount)(void);
N_NIMCALL(void, quit_y2WuTG82qH44FHhQsKXOCg)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_LJ9cWUOIKdJkv7vFbyFx9a6g_5)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void*, GetThreadLocalVars)(void);
N_NIMCALL(void*, threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg)(NI32 dwTlsIndex);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(FlowVarObj_a5vp0WwZohkMPdG8GkZciw*, nimCreateFlowVar_xO39aB5u4tZXwMOqMul3KoQ)(void);
N_NIMCALL(void, fvFinalizer_W4h8xN17XW4JRY8Mrf8lfg)(FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv);
N_NIMCALL(NimStringDesc*, roof__LbfEYJu3cF61FE9coTsJenA)(FlowVarObj_a5vp0WwZohkMPdG8GkZciw* fv);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_LJ9cWUOIKdJkv7vFbyFx9a6g_7)(void);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
N_NIMCALL(void, nimSpawn3)(TY_fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_NIMCALL(void, readLineWrapper_BAHGwgmfoNdWVRzGBBvsEw)(void* thread, void* args);
N_NIMCALL(void, genericDeepCopy)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_NIMCALL(void, nimGCref)(void* p);
N_NIMCALL(void, nimFlowVarSignal)(FlowVarBaseObj_CJfwFDAb1ST4bu6G9bMAYbg* fv);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
static N_INLINE(void, initThreadVarsEmulation)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, clientDatInit000)(void);
NimStringDesc* svrAddr_zuVK9akiosOY9aSxddu8OzZg;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern NI32 globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;
FlowVarObj_a5vp0WwZohkMPdG8GkZciw* msg_Jw6UrtCj7KesCe1xuXcIpw;
extern TNimType NTI_VAHnGVFOjU5gFagNSbMOOg_;
extern TNimType NTI_7BHnQsEj49a9c6QtudqWTo1w_;
extern GcThread_hgJQSlfXDOK3SwSHjeZBXg mainThread_6r3APOnKvB9aL9atazGvT52A;
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_2, "chat application started", 24);
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_3, "Please specify the server address, e.g. ", 40);
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_4, " localhost", 10);
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_6, "connecting to ", 14);
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_8, "Sending \"", 9);
STRING_LITERAL(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_9, "\"", 1);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_LJ9cWUOIKdJkv7vFbyFx9a6g_5)(void) {
	nimGCvisit((void*)svrAddr_zuVK9akiosOY9aSxddu8OzZg, 0);
}

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	T1_ = (NI)0;
	{
		if (!(NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	NimThreadVars* NimTV_;
	nimfr_("rtlAddZCT", "gc.nim")
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&NimTV_->gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(281, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(363, "system.nim");
		nimln_(281, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(282, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(363, "system.nim");
		nimln_(282, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_LJ9cWUOIKdJkv7vFbyFx9a6g_7)(void) {
	nimGCvisit((void*)msg_Jw6UrtCj7KesCe1xuXcIpw, 0);
}

N_NIMCALL(void, readLineWrapper_BAHGwgmfoNdWVRzGBBvsEw)(void* thread, void* args) {
	FILE* colontmp_;
	FlowVarObj_a5vp0WwZohkMPdG8GkZciw* colontmp__2;
	FILE* T1_;
	nimfr_("readLineWrapper", "client.nim")
	colontmp_ = (FILE*)0;
	nimln_(8, "client.nim");
	colontmp__2 = (*((Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ*) (args))).fv1;
	T1_ = (FILE*)0;
	T1_ = (*((Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ*) (args))).f0;
	genericDeepCopy((void*)(&colontmp_), (void*)(&T1_), (&NTI_7BHnQsEj49a9c6QtudqWTo1w_));
	(*colontmp__2).Sup.owner = thread;
	nimArgsPassingDone(thread);
	(*colontmp__2).Sup.data = readLine_fPRnXwDTqtynUYGl4OixAg(colontmp_);
	nimGCref((*colontmp__2).Sup.data);
	nimFlowVarSignal(colontmp__2);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}

static N_INLINE(void, initThreadVarsEmulation)(void) {
	globalsSlot_ciXDZu9c27pHpCRMoz4RIgw = TlsAlloc();
	TlsSetValue(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw, ((void*) ((&mainThread_6r3APOnKvB9aL9atazGvT52A))));
}
void PreMainInner(void) {
	systemInit000();
	stdlib_locksDatInit000();
	stdlib_sharedlistDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_cpuloadDatInit000();
	stdlib_threadpoolDatInit000();
	clientDatInit000();
	stdlib_locksInit000();
	stdlib_sharedlistInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_cpuinfoInit000();
	stdlib_cpuloadInit000();
	stdlib_threadpoolInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initThreadVarsEmulation();
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NI NimThreadVarsSize(){return (NI)sizeof(NimThreadVars);}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("client", "client.nim")
nimRegisterGlobalMarker(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_5);
nimRegisterGlobalMarker(TM_LJ9cWUOIKdJkv7vFbyFx9a6g_7);
	nimln_(2, "client.nim");
	printf("%s\015\012", ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_2)? (((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_2))->data:"nil");
	fflush(stdout);
	nimln_(3, "client.nim");
	{
		NI T3_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		T3_ = (NI)0;
		T3_ = nosparamCount();
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(4, "client.nim");
		T6_ = (NimStringDesc*)0;
		T7_ = (NimStringDesc*)0;
		T7_ = nosgetAppFilename();
		T6_ = rawNewString(T7_->Sup.len + 50);
appendString(T6_, ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_3));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_4));
		quit_y2WuTG82qH44FHhQsKXOCg(T6_, ((NI) 1));
	}
	LA4_: ;
	nimln_(5, "client.nim");
	asgnRefNoCycle((void**) (&svrAddr_zuVK9akiosOY9aSxddu8OzZg), nosparamStr(((NI) 1)));
	nimln_(6, "client.nim");
	printf("%s%s\015\012", ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_6)? (((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_6))->data:"nil", svrAddr_zuVK9akiosOY9aSxddu8OzZg? (svrAddr_zuVK9akiosOY9aSxddu8OzZg)->data:"nil");
	fflush(stdout);
	{
		nimln_(7, "client.nim");
		while (1) {
			Env_clientdotnim__2yAg9c6QDoQAV9aRfpkVhxVQ scratch;
			NimStringDesc* T10_;
			asgnRef((void**) (&msg_Jw6UrtCj7KesCe1xuXcIpw), NIM_NIL);
			nimln_(8, "client.nim");
			memset((void*)(&scratch), 0, sizeof(scratch));
			scratch.f0 = stdin;
			nimln_(194, "threadpool.nim");
			scratch.fv1 = nimCreateFlowVar_xO39aB5u4tZXwMOqMul3KoQ();
			nimln_(8, "client.nim");
			nimFlowVarCreateSemaphore(scratch.fv1);
			nimSpawn3(readLineWrapper_BAHGwgmfoNdWVRzGBBvsEw, (&scratch));
			asgnRef((void**) (&msg_Jw6UrtCj7KesCe1xuXcIpw), scratch.fv1);
			nimln_(9, "client.nim");
			T10_ = (NimStringDesc*)0;
			T10_ = roof__LbfEYJu3cF61FE9coTsJenA(msg_Jw6UrtCj7KesCe1xuXcIpw);
			printf("%s%s%s\015\012", ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_8)? (((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_8))->data:"nil", T10_? (T10_)->data:"nil", ((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_9)? (((NimStringDesc*) &TM_LJ9cWUOIKdJkv7vFbyFx9a6g_9))->data:"nil");
			fflush(stdout);
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, clientDatInit000)(void) {
}

