/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\ZACH\Documents\mingw64\bin\gcc.exe -c  -w  -IC:\Users\ZACH\Documents\nim-0.17.0\lib -o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\protocol.o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\protocol.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <setjmp.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Message_xoh5rXnWwbqFwYAt1NMfNw Message_xoh5rXnWwbqFwYAt1NMfNw;
typedef struct JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct OrderedTable_AF39bJ7XDr6gpANuGpxkHrw OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct TY_MlAD6nAPq9bHKla9cWiIZP0g TY_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct TY_oLpBKXzW3hF9aCVMo5EymfQ TY_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TY_awOivLjlO76sGdHY7nQUjQ TY_awOivLjlO76sGdHY7nQUjQ;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Message_xoh5rXnWwbqFwYAt1NMfNw  {
NimStringDesc* username;
NimStringDesc* message;
};
typedef NU8 JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct  OrderedTable_AF39bJ7XDr6gpANuGpxkHrw  {
TY_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct  JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q  {
JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {TY_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct TY_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  TY_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct TY_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, parseMessage_o4A5gwcp9ceItjXMTgniqGw)(NimStringDesc* data, Message_xoh5rXnWwbqFwYAt1NMfNw* Result);
N_NIMCALL(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_q2jt59czHU4BW88Mb7EJDUA)(NimStringDesc* buffer);
N_NIMCALL(NimStringDesc*, getStr_z2Itmc4KJ7uMBtaTVQ09cqw)(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NimStringDesc* default_0);
static N_INLINE(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, dollar__LxBYfYOjiFWZxWy9aGrTf8g)(Message_xoh5rXnWwbqFwYAt1NMfNw x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_8)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_11)(void);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_16)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_19)(void);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, protocolDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NimStringDesc* data_wmneBXHEzQdPK5c9bnqvwOA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
Message_xoh5rXnWwbqFwYAt1NMfNw parsed_lWJOpCvZ5TvsfgdvTVUOuw;
TNimType NTI_xoh5rXnWwbqFwYAt1NMfNw_;
NimStringDesc* data_wmneBXHEzQdPK5c9bnqvwOA_2;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Message_xoh5rXnWwbqFwYAt1NMfNw parsed_lWJOpCvZ5TvsfgdvTVUOuw_2;
extern TNimType NTI_4avqtqpbmyD9bxH9bUmO9b0yw_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_2, "not isNil(node) ", 16);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_3, "node.kind == JObject ", 21);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_4, "fields", 6);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_5, "username", 8);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_6, "", 0);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_7, "message", 7);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_9, "    {\015\012    \"username\": \"Zachary\",\015\012    \"message\": \"Howdy there\""
"\015\012    }\015\012    ", 76);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_12, "Zachary", 7);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_13, "parsed.username == \"Zachary\" ", 29);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_14, "Howdy there", 11);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_15, "parsed.message == \"Howdy there\" ", 32);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_17, "foobar", 6);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_20, "false ", 6);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_21, "true ", 5);
STRING_LITERAL(TM_6YwNZhDxCxVxXWRgvYG9cPw_22, "All Tests Passed", 16);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q** T9_;
	nimfr_("[]", "json.nim")
	result = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(880, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_2));
	}
	LA3_: ;
	nimln_(881, "json.nim");
	{
		if (!!(((*node).kind == ((JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_3));
	}
	LA7_: ;
	nimln_(884, "json.nim");
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_4));
	T9_ = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	T9_ = X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg((&(*node).kindU.S6.fields), name);
	result = (*T9_);
	popFrame();
	return result;
}

N_NIMCALL(void, parseMessage_o4A5gwcp9ceItjXMTgniqGw)(NimStringDesc* data, Message_xoh5rXnWwbqFwYAt1NMfNw* Result) {
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* dataJson;
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T2_;
	nimfr_("parseMessage", "protocol.nim")
	nimln_(8, "protocol.nim");
	dataJson = parseJson_q2jt59czHU4BW88Mb7EJDUA(data);
	nimln_(9, "protocol.nim");
	T1_ = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(dataJson, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_5));
	unsureAsgnRef((void**) (&(*Result).username), getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T1_, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_6)));
	nimln_(10, "protocol.nim");
	T2_ = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T2_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(dataJson, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_7));
	unsureAsgnRef((void**) (&(*Result).message), getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T2_, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_6)));
	popFrame();
}
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_8)(void) {
	nimGCvisit((void*)data_wmneBXHEzQdPK5c9bnqvwOA, 0);
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_11)(void) {
	nimGCvisit((void*)parsed_lWJOpCvZ5TvsfgdvTVUOuw.username, 0);
	nimGCvisit((void*)parsed_lWJOpCvZ5TvsfgdvTVUOuw.message, 0);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_16)(void) {
	nimGCvisit((void*)data_wmneBXHEzQdPK5c9bnqvwOA_2, 0);
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_NIMCALL(void, TM_6YwNZhDxCxVxXWRgvYG9cPw_19)(void) {
	nimGCvisit((void*)parsed_lWJOpCvZ5TvsfgdvTVUOuw_2.username, 0);
	nimGCvisit((void*)parsed_lWJOpCvZ5TvsfgdvTVUOuw_2.message, 0);
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim")
	result = (Exception*)0;
	nimln_(3171, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(281, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(363, "system.nim");
		nimln_(281, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(282, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(363, "system.nim");
		nimln_(282, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), NIM_NIL);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_jsonDatInit000();
	protocolDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_jsonInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("protocol", "protocol.nim")
nimRegisterGlobalMarker(TM_6YwNZhDxCxVxXWRgvYG9cPw_8);
nimRegisterGlobalMarker(TM_6YwNZhDxCxVxXWRgvYG9cPw_11);
nimRegisterGlobalMarker(TM_6YwNZhDxCxVxXWRgvYG9cPw_16);
nimRegisterGlobalMarker(TM_6YwNZhDxCxVxXWRgvYG9cPw_19);
	{
		NimStringDesc* T2_;
		NimStringDesc* T3_;
		nimln_(14, "protocol.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = data_wmneBXHEzQdPK5c9bnqvwOA; data_wmneBXHEzQdPK5c9bnqvwOA = copyStringRC1(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_9));
		if (T2_) nimGCunrefNoCycle(T2_);
		nimln_(20, "protocol.nim");
		chckNil((void*)(&parsed_lWJOpCvZ5TvsfgdvTVUOuw));
		genericReset((void*)(&parsed_lWJOpCvZ5TvsfgdvTVUOuw), (&NTI_xoh5rXnWwbqFwYAt1NMfNw_));
		parseMessage_o4A5gwcp9ceItjXMTgniqGw(data_wmneBXHEzQdPK5c9bnqvwOA, (&parsed_lWJOpCvZ5TvsfgdvTVUOuw));
		nimln_(21, "protocol.nim");
		T3_ = (NimStringDesc*)0;
		T3_ = dollar__LxBYfYOjiFWZxWy9aGrTf8g(parsed_lWJOpCvZ5TvsfgdvTVUOuw);
		printf("%s\015\012", T3_? (T3_)->data:"nil");
		fflush(stdout);
		nimln_(22, "protocol.nim");
		{
			if (!!(eqStrings(parsed_lWJOpCvZ5TvsfgdvTVUOuw.username, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_12)))) goto LA6_;
			raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_13));
		}
		LA6_: ;
		nimln_(23, "protocol.nim");
		{
			if (!!(eqStrings(parsed_lWJOpCvZ5TvsfgdvTVUOuw.message, ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_14)))) goto LA10_;
			raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_15));
		}
		LA10_: ;
	}
	{
		NimStringDesc* T13_;
		TSafePoint TM_6YwNZhDxCxVxXWRgvYG9cPw_18;
		nimln_(25, "protocol.nim");
		T13_ = (NimStringDesc*)0;
		T13_ = data_wmneBXHEzQdPK5c9bnqvwOA_2; data_wmneBXHEzQdPK5c9bnqvwOA_2 = copyStringRC1(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_17));
		if (T13_) nimGCunrefNoCycle(T13_);
		nimln_(26, "protocol.nim");
		pushSafePoint(&TM_6YwNZhDxCxVxXWRgvYG9cPw_18);
		TM_6YwNZhDxCxVxXWRgvYG9cPw_18.status = setjmp(TM_6YwNZhDxCxVxXWRgvYG9cPw_18.context);
		if (TM_6YwNZhDxCxVxXWRgvYG9cPw_18.status == 0) {
			nimln_(27, "protocol.nim");
			chckNil((void*)(&parsed_lWJOpCvZ5TvsfgdvTVUOuw_2));
			genericReset((void*)(&parsed_lWJOpCvZ5TvsfgdvTVUOuw_2), (&NTI_xoh5rXnWwbqFwYAt1NMfNw_));
			parseMessage_o4A5gwcp9ceItjXMTgniqGw(data_wmneBXHEzQdPK5c9bnqvwOA_2, (&parsed_lWJOpCvZ5TvsfgdvTVUOuw_2));
			nimln_(28, "protocol.nim");
			{
				if (!NIM_TRUE) goto LA17_;
				raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_20));
			}
			LA17_: ;
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
			if (isObj(getCurrentException()->Sup.m_type, (&NTI_4avqtqpbmyD9bxH9bUmO9b0yw_))) {
				TM_6YwNZhDxCxVxXWRgvYG9cPw_18.status = 0;
				nimln_(30, "protocol.nim");
				{
					if (!NIM_FALSE) goto LA23_;
					raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_21));
				}
				LA23_: ;
				popCurrentException();
			}
			else			{
				TM_6YwNZhDxCxVxXWRgvYG9cPw_18.status = 0;
				nimln_(32, "protocol.nim");
				{
					if (!NIM_TRUE) goto LA28_;
					raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_20));
				}
				LA28_: ;
				popCurrentException();
			}
		}
		if (TM_6YwNZhDxCxVxXWRgvYG9cPw_18.status != 0) reraiseException();
		nimln_(33, "protocol.nim");
		printf("%s\015\012", ((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_22)? (((NimStringDesc*) &TM_6YwNZhDxCxVxXWRgvYG9cPw_22))->data:"nil");
		fflush(stdout);
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, protocolDatInit000)(void) {
static TNimNode* TM_6YwNZhDxCxVxXWRgvYG9cPw_10[2];
static TNimNode TM_6YwNZhDxCxVxXWRgvYG9cPw_0[3];
NTI_xoh5rXnWwbqFwYAt1NMfNw_.size = sizeof(Message_xoh5rXnWwbqFwYAt1NMfNw);
NTI_xoh5rXnWwbqFwYAt1NMfNw_.kind = 18;
NTI_xoh5rXnWwbqFwYAt1NMfNw_.base = 0;
NTI_xoh5rXnWwbqFwYAt1NMfNw_.flags = 2;
TM_6YwNZhDxCxVxXWRgvYG9cPw_10[0] = &TM_6YwNZhDxCxVxXWRgvYG9cPw_0[1];
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[1].kind = 1;
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[1].offset = offsetof(Message_xoh5rXnWwbqFwYAt1NMfNw, username);
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[1].name = "username";
TM_6YwNZhDxCxVxXWRgvYG9cPw_10[1] = &TM_6YwNZhDxCxVxXWRgvYG9cPw_0[2];
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[2].kind = 1;
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[2].offset = offsetof(Message_xoh5rXnWwbqFwYAt1NMfNw, message);
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[2].name = "message";
TM_6YwNZhDxCxVxXWRgvYG9cPw_0[0].len = 2; TM_6YwNZhDxCxVxXWRgvYG9cPw_0[0].kind = 2; TM_6YwNZhDxCxVxXWRgvYG9cPw_0[0].sons = &TM_6YwNZhDxCxVxXWRgvYG9cPw_10[0];
NTI_xoh5rXnWwbqFwYAt1NMfNw_.node = &TM_6YwNZhDxCxVxXWRgvYG9cPw_0[0];
}

