/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\ZACH\Documents\mingw64\bin\gcc.exe -c  -w  -IC:\Users\ZACH\Documents\nim-0.17.0\lib -o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_tables.o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct OrderedTable_AF39bJ7XDr6gpANuGpxkHrw OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct TY_MlAD6nAPq9bHKla9cWiIZP0g TY_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_awOivLjlO76sGdHY7nQUjQ TY_awOivLjlO76sGdHY7nQUjQ;
typedef struct JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct KeyError_ifYAhUumNzWR9c9cN9amyJLtg KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct ValueError_Gi06FkNeykJn7mrqRZYrkA ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TY_oLpBKXzW3hF9aCVMo5EymfQ TY_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  OrderedTable_AF39bJ7XDr6gpANuGpxkHrw  {
TY_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TY_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  ValueError_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
struct  KeyError_ifYAhUumNzWR9c9cN9amyJLtg  {
  ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct  JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q  {
JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {TY_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  TY_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct TY_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count);
N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op);
N_NIMCALL(NIM_BOOL, isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, rawGet_ejrpxsNAZJyHhQhopPiwJA)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, enlarge_eOZs9auXoZM0glvDlTLHszQ)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t);
N_NIMCALL(NI, rawGetKnownHC_DycNfqFZryzkgIAk9bw7xSQ)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawInsert_PJEZeDCLfp6559cI0Hhn8lg)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, TY_MlAD6nAPq9bHKla9cWiIZP0g** data, NimStringDesc* key, JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NI, rawGet_WyEeYQHki9bxcrycmQ047tQtables)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI* hc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_AF39bJ7XDr6gpANuGpxkHrw_;
TNimType NTI_awOivLjlO76sGdHY7nQUjQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_zfzzuQ8txrdZAYK0WGWpHg_;
TNimType NTI_MlAD6nAPq9bHKla9cWiIZP0g_;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_2, "\015\012  counter < length ", 21);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_12, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_20, "key not found: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isEmpty", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(363, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_4;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_5;
	nimfr_("mustRehash", "tableimpl.nim")
	result = (NIM_BOOL)0;
	nimln_(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_2));
	}
	LA3_: ;
	nimln_(25, "tableimpl.nim");
	T5_ = (NIM_BOOL)0;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_3 = mulInt(length, ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_3) < (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (T5_) goto LA6_;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_5 = subInt(length, counter);
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_6;
	nimfr_("nextTry", "tableimpl.nim")
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_6 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_6) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_9;
	nimfr_("rightSize", "tables.nim")
	result = (NI)0;
	nimln_(136, "tables.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_7 = mulInt(((NI) (count)), ((NI) 3));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_8 = divInt(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_7))), ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_9 = addInt(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_8))), ((NI) 4));
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_9))));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* a;
	NI T1_;
	a = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, initOrderedTable_PHRF9cHqhXGiWC9cIiRW9bTWw)(NI initialSize, OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* Result) {
	nimfr_("initOrderedTable", "tables.nim")
	nimln_(621, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_12));
	}
	LA4_: ;
	nimln_(622, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(623, "tables.nim");
	(*Result).first = ((NI) -1);
	nimln_(624, "tables.nim");
	(*Result).last = ((NI) -1);
	nimln_(625, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NI, rawGet_ejrpxsNAZJyHhQhopPiwJA)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_13;
	nimfr_("rawGet", "tables.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = ((*t).data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = eqStrings((*t).data->data[h].Field2, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_13 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_13);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim")
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim")
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim")
	nimln_(288, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(363, "system.nim");
		nimln_(288, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(289, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(290, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(291, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(363, "system.nim");
		nimln_(291, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(292, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(293, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(294, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(295, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, rawGetKnownHC_DycNfqFZryzkgIAk9bw7xSQ)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_15;
	nimfr_("rawGetKnownHC", "tables.nim")
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)(hc & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T3_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T3_ = (NIM_BOOL)0;
			T3_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T3_) goto LA2;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T6_ = ((*t).data->data[h].Field0 == hc);
				if (!(T6_)) goto LA7_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T6_ = eqStrings((*t).data->data[h].Field2, key);
				LA7_: ;
				if (!T6_) goto LA8_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA8_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_15 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_15);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim")
	nimln_(270, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(272, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(273, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(void, rawInsert_PJEZeDCLfp6559cI0Hhn8lg)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, TY_MlAD6nAPq9bHKla9cWiIZP0g** data, NimStringDesc* key, JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val, NI hc, NI h) {
	NimStringDesc* T1_;
	nimfr_("rawInsert", "tables.nim")
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	asgnRefNoCycle((void**) (&(*data)->data[h].Field3), val);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(579, "tables.nim");
	(*data)->data[h].Field1 = ((NI) -1);
	nimln_(580, "tables.nim");
	{
		if (!((*t).first < ((NI) 0))) goto LA4_;
		(*t).first = h;
	}
	LA4_: ;
	nimln_(581, "tables.nim");
	{
		if (!(((NI) 0) <= (*t).last)) goto LA8_;
		if ((NU)((*t).last) >= (NU)((*data)->Sup.len)) raiseIndexError();
		(*data)->data[(*t).last].Field1 = h;
	}
	LA8_: ;
	nimln_(582, "tables.nim");
	(*t).last = h;
	popFrame();
}

N_NIMCALL(void, enlarge_eOZs9auXoZM0glvDlTLHszQ)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* n;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_14;
	NI h;
	TY_MlAD6nAPq9bHKla9cWiIZP0g* T1_;
	nimfr_("enlarge", "tables.nim")
	n = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	nimln_(586, "tables.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_14 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_14), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(587, "tables.nim");
	h = (*t).first;
	nimln_(588, "tables.nim");
	(*t).first = ((NI) -1);
	nimln_(589, "tables.nim");
	(*t).last = ((NI) -1);
	nimln_(590, "tables.nim");
	T1_ = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	T1_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T1_;
	{
		nimln_(591, "tables.nim");
		while (1) {
			NI nxt;
			if (!(((NI) 0) <= h)) goto LA3;
			nimln_(592, "tables.nim");
			if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
			nxt = n->data[h].Field1;
			nimln_(593, "tables.nim");
			{
				NIM_BOOL T6_;
				NI j;
				NI T9_;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_16;
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				T6_ = (NIM_BOOL)0;
				T6_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(n->data[h].Field0);
				if (!T6_) goto LA7_;
				nimln_(594, "tables.nim");
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				T9_ = (NI)0;
				T9_ = rawGetKnownHC_DycNfqFZryzkgIAk9bw7xSQ((&(*t)), n->data[h].Field2, n->data[h].Field0);
				TM_4SoG2KRQy3oMm9aUzSLtGrA_16 = subInt(((NI) -1), T9_);
				j = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_16);
				nimln_(595, "tables.nim");
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				rawInsert_PJEZeDCLfp6559cI0Hhn8lg(t, (&(*t).data), n->data[h].Field2, n->data[h].Field3, n->data[h].Field0, j);
			}
			LA7_: ;
			nimln_(596, "tables.nim");
			h = nxt;
		} LA3: ;
	}
	popFrame();
}

N_NIMCALL(void, X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val) {
	NI hc;
	NI index;
	nimfr_("[]=", "tables.nim")
	hc = (NI)0;
	nimln_(98, "tableimpl.nim");
	index = rawGet_ejrpxsNAZJyHhQhopPiwJA((&(*t)), key, (&hc));
	nimln_(600, "tables.nim");
	{
		nimln_(99, "tableimpl.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*t).data->data[index].Field3), val);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_17;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_18;
		nimln_(89, "tableimpl.nim");
		{
			NIM_BOOL T8_;
			nimln_(117, "tables.nim");
			T8_ = (NIM_BOOL)0;
			T8_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!T8_) goto LA9_;
			nimln_(90, "tableimpl.nim");
			enlarge_eOZs9auXoZM0glvDlTLHszQ(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_DycNfqFZryzkgIAk9bw7xSQ((&(*t)), key, hc);
		}
		LA9_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_17 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_17);
		nimln_(93, "tableimpl.nim");
		rawInsert_PJEZeDCLfp6559cI0Hhn8lg(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_18 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_18);
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, hasKey_6zZzy9aTG3euSh9bJ9bh9aFOqA)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	nimfr_("hasKey", "tables.nim")
	result = (NIM_BOOL)0;
	hc = (NI)0;
	nimln_(569, "tables.nim");
	T1_ = (NI)0;
	T1_ = rawGet_ejrpxsNAZJyHhQhopPiwJA(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_WyEeYQHki9bxcrycmQ047tQtables)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_19;
	nimfr_("rawGet", "tableimpl.nim")
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	h = (NI)((*hc) & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T7_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			T7_ = (NIM_BOOL)0;
			T7_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[h].Field0);
			if (!T7_) goto LA6;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = ((*t).data->data[h].Field0 == (*hc));
				if (!(T10_)) goto LA11_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T10_ = eqStrings((*t).data->data[h].Field2, key);
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_19 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_19);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim")
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim")
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim")
	nimln_(281, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(363, "system.nim");
		nimln_(281, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(282, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(363, "system.nim");
		nimln_(282, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key) {
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q** result;
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim")
	result = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_WyEeYQHki9bxcrycmQ047tQtables((&(*t)), key, (&hc));
	nimln_(554, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = &(*t).data->data[index].Field3;
	}
	goto LA1_;
	LA3_: ;
	{
		KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2634, "system.nim");
		e = (KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(554, "tables.nim");
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_20));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2629, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, getOrDefault_eiC0QjqFEL1eMy9c1lEf0RA)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key) {
	JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	NI hc;
	NI index;
	nimfr_("getOrDefault", "tables.nim")
	result = (JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	hc = (NI)0;
	nimln_(158, "tables.nim");
	index = rawGet_WyEeYQHki9bxcrycmQ047tQtables(t, key, (&hc));
	nimln_(563, "tables.nim");
	{
		nimln_(159, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (*t).data->data[index].Field3;
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, del_kBvF4V6kGI5xT2NUPtOV5g)(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* n;
	NI h;
	TY_MlAD6nAPq9bHKla9cWiIZP0g* T1_;
	NI hc;
	NI res;
	nimfr_("del", "tables.nim")
	n = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	nimln_(809, "tables.nim");
	n = (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g_), ((NI)chckRange(((*t).data ? (*t).data->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(810, "tables.nim");
	h = (*t).first;
	nimln_(811, "tables.nim");
	(*t).first = ((NI) -1);
	nimln_(812, "tables.nim");
	(*t).last = ((NI) -1);
	nimln_(813, "tables.nim");
	T1_ = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	T1_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T1_;
	nimln_(814, "tables.nim");
	res = (NI)0;
	res = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	nimln_(49, "tableimpl.nim");
	{
		if (!(res == ((NI) 0))) goto LA4_;
		nimln_(45, "tableimpl.nim");
		res = ((NI) 314159265);
	}
	LA4_: ;
	hc = res;
	{
		nimln_(815, "tables.nim");
		while (1) {
			NI nxt;
			if (!(((NI) 0) <= h)) goto LA7;
			nimln_(816, "tables.nim");
			if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
			nxt = n->data[h].Field1;
			nimln_(817, "tables.nim");
			{
				NIM_BOOL T10_;
				if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
				T10_ = (NIM_BOOL)0;
				T10_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(n->data[h].Field0);
				if (!T10_) goto LA11_;
				nimln_(818, "tables.nim");
				{
					NIM_BOOL T15_;
					NI TM_4SoG2KRQy3oMm9aUzSLtGrA_21;
					T15_ = (NIM_BOOL)0;
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					T15_ = (n->data[h].Field0 == hc);
					if (!(T15_)) goto LA16_;
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					T15_ = eqStrings(n->data[h].Field2, key);
					LA16_: ;
					if (!T15_) goto LA17_;
					nimln_(819, "tables.nim");
					TM_4SoG2KRQy3oMm9aUzSLtGrA_21 = subInt((*t).counter, ((NI) 1));
					(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_21);
				}
				goto LA13_;
				LA17_: ;
				{
					NI j;
					NI T20_;
					NI TM_4SoG2KRQy3oMm9aUzSLtGrA_22;
					nimln_(821, "tables.nim");
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					T20_ = (NI)0;
					T20_ = rawGetKnownHC_DycNfqFZryzkgIAk9bw7xSQ((&(*t)), n->data[h].Field2, n->data[h].Field0);
					TM_4SoG2KRQy3oMm9aUzSLtGrA_22 = subInt(((NI) -1), T20_);
					j = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_22);
					nimln_(822, "tables.nim");
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(h) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_PJEZeDCLfp6559cI0Hhn8lg(t, (&(*t).data), n->data[h].Field2, n->data[h].Field3, n->data[h].Field0, j);
				}
				LA13_: ;
			}
			LA11_: ;
			nimln_(823, "tables.nim");
			h = nxt;
		} LA7: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr_("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_10[4];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_11[4];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
NTI_AF39bJ7XDr6gpANuGpxkHrw_.size = sizeof(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw);
NTI_AF39bJ7XDr6gpANuGpxkHrw_.kind = 18;
NTI_AF39bJ7XDr6gpANuGpxkHrw_.base = 0;
NTI_AF39bJ7XDr6gpANuGpxkHrw_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_awOivLjlO76sGdHY7nQUjQ_.size = sizeof(TY_awOivLjlO76sGdHY7nQUjQ);
NTI_awOivLjlO76sGdHY7nQUjQ_.kind = 18;
NTI_awOivLjlO76sGdHY7nQUjQ_.base = 0;
NTI_awOivLjlO76sGdHY7nQUjQ_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[3] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field3);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_zfzzuQ8txrdZAYK0WGWpHg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "Field3";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 4; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0];
NTI_awOivLjlO76sGdHY7nQUjQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_MlAD6nAPq9bHKla9cWiIZP0g_.size = sizeof(TY_MlAD6nAPq9bHKla9cWiIZP0g*);
NTI_MlAD6nAPq9bHKla9cWiIZP0g_.kind = 24;
NTI_MlAD6nAPq9bHKla9cWiIZP0g_.base = (&NTI_awOivLjlO76sGdHY7nQUjQ_);
NTI_MlAD6nAPq9bHKla9cWiIZP0g_.flags = 2;
NTI_MlAD6nAPq9bHKla9cWiIZP0g_.marker = Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_MlAD6nAPq9bHKla9cWiIZP0g_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].offset = offsetof(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw, first);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "first";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[3] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].offset = offsetof(OrderedTable_AF39bJ7XDr6gpANuGpxkHrw, last);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].name = "last";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 4; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0];
NTI_AF39bJ7XDr6gpANuGpxkHrw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
}

