/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\ZACH\Documents\mingw64\bin\gcc.exe -c  -w  -IC:\Users\ZACH\Documents\nim-0.17.0\lib -o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_ospaths.o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_ospaths.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct GcThread_hgJQSlfXDOK3SwSHjeZBXg GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct TY_UV3llMMYFckfui8YMBuUZA TY_UV3llMMYFckfui8YMBuUZA;
typedef struct TY_7q7q3E6Oj24ZNVJb9aonhAg TY_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct Exception Exception;
typedef struct TY_WF89a8QyKeDCh4DYWTmSiBg TY_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TSafePoint TSafePoint;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct SharedList_9cWkTIPQvNw7gFHMOEzMCLw SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF TY_SBX73RxxTewX4sqVYGfdEA[1001];
struct  GcThread_hgJQSlfXDOK3SwSHjeZBXg  {
TY_SBX73RxxTewX4sqVYGfdEA tls;
};
struct TY_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct TY_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_NIMCALL_PTR(NIM_BOOL, TY_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} TY_IIomJ6ptE6vfJ5zRbATgkQ;
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  SharedList_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
CRITICAL_SECTION lock;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
};
struct TY_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  TY_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
typedef struct {TY_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
TY_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_LLyFo9bsdu1ZXMDvAe8DhrQ;
TY_sM4lkSb7zS6F7OVMvW9cffQ* environment_mlhK49b6YMgc9cgrcYkKq9a3g;
TY_sM4lkSb7zS6F7OVMvW9cffQ* ownArgv_WVJ54JSHy7VxacV39bwBPFA;
NIM_BOOL isSlave_t9a8wsVVRYqGEKhg1vb49b3g;
} NimThreadVars;
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void*, GetThreadLocalVars)(void);
N_NIMCALL(void*, threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg)(NI32 dwTlsIndex);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY_UV3llMMYFckfui8YMBuUZA* Result);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nostailDir)(NimStringDesc* path);
N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, slashdotdotslash__lXoMhn1ZYc9cAJa9bfA61msg_2)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, normExt_3yxSdoh5oykvpUqYYeaz2g)(NimStringDesc* ext);
N_NIMCALL(NI, searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2)(NimStringDesc* path);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NI, noscmpPaths)(NimStringDesc* pathA, NimStringDesc* pathB);
N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path, NimStringDesc* drive);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
extern NI32 globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_8, "", 0);
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_29, ":\\", 2);
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_30, "\\", 1);
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_31, ".", 1);
STRING_LITERAL(TM_jvWQYw9bcuYhftfPX2ynPeg_34, "..\\", 3);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	T1_ = (NI)0;
	{
		if (!(NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*NimTV_->framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr_("joinPath", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(196, "ospaths.nim");
	{
		if (!((head ? head->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(197, "ospaths.nim");
		result = copyString(tail);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_2;
		nimln_(198, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_2 = subInt((head ? head->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)) > (NU)(head->Sup.len)) raiseIndexError();
		if (!(((NU8)(head->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)])) == ((NU8)(92)) || ((NU8)(head->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_2)])) == ((NU8)(47)))) goto LA6_;
		nimln_(199, "ospaths.nim");
		{
			NimStringDesc* T12_;
			NimStringDesc* T13_;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(92)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA10_;
			nimln_(200, "ospaths.nim");
			T12_ = (NimStringDesc*)0;
			T13_ = (NimStringDesc*)0;
			T13_ = copyStr(tail, ((NI) 1));
			T12_ = rawNewString(head->Sup.len + T13_->Sup.len + 0);
appendString(T12_, head);
appendString(T12_, T13_);
			result = T12_;
		}
		goto LA8_;
		LA10_: ;
		{
			NimStringDesc* T15_;
			nimln_(202, "ospaths.nim");
			T15_ = (NimStringDesc*)0;
			T15_ = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(T15_, head);
appendString(T15_, tail);
			result = T15_;
		}
		LA8_: ;
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(204, "ospaths.nim");
		{
			NimStringDesc* T21_;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(92)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA19_;
			nimln_(205, "ospaths.nim");
			T21_ = (NimStringDesc*)0;
			T21_ = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(T21_, head);
appendString(T21_, tail);
			result = T21_;
		}
		goto LA17_;
		LA19_: ;
		{
			NimStringDesc* T23_;
			nimln_(207, "ospaths.nim");
			T23_ = (NimStringDesc*)0;
			T23_ = rawNewString(head->Sup.len + tail->Sup.len + 1);
appendString(T23_, head);
appendChar(T23_, 92);
appendString(T23_, tail);
			result = T23_;
		}
		LA17_: ;
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partsLen_0) {
	NimStringDesc* result;
	nimfr_("joinPath", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(214, "ospaths.nim");
	if ((NU)(((NI) 0)) >= (NU)(partsLen_0)) raiseIndexError();
	result = copyString(parts[((NI) 0)]);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(215, "ospaths.nim");
		colontmp_ = (partsLen_0-1);
		nimln_(1955, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_3;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1957, "system.nim");
				i = res;
				nimln_(216, "ospaths.nim");
				if ((NU)(i) >= (NU)(partsLen_0)) raiseIndexError();
				result = nosjoinPath(result, parts[i]);
				nimln_(1976, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr_("/", "ospaths.nim")
{	result = (NimStringDesc*)0;
	nimln_(228, "ospaths.nim");
	result = nosjoinPath(head, tail);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY_UV3llMMYFckfui8YMBuUZA* Result) {
	NI sepPos;
	nimfr_("splitPath", "ospaths.nim")
	nimln_(243, "ospaths.nim");
	sepPos = ((NI) -1);
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_4;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(244, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_4 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_4);
		nimln_(1943, "system.nim");
		res = colontmp_;
		{
			nimln_(1944, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_5;
				nimln_(244, "ospaths.nim");
				if (!(((NI) 0) <= res)) goto LA3;
				nimln_(1945, "system.nim");
				i = res;
				nimln_(245, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(92)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA6_;
					nimln_(246, "ospaths.nim");
					sepPos = i;
					nimln_(247, "ospaths.nim");
					goto LA1;
				}
				LA6_: ;
				nimln_(1946, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_5 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_5);
			} LA3: ;
		}
	} LA1: ;
	nimln_(248, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_6;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_7;
		if (!(((NI) 0) <= sepPos)) goto LA10_;
		nimln_(249, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_6 = subInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_6)));
		nimln_(250, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_7 = addInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStr(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_7)));
	}
	goto LA8_;
	LA10_: ;
	{
		nimln_(252, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
		nimln_(253, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(path));
	}
	LA8_: ;
	popFrame();
}

N_NIMCALL(NI, parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA)(NimStringDesc* path) {
	NI result;
	NI q;
	nimfr_("parentDirPos", "ospaths.nim")
{	result = (NI)0;
	nimln_(256, "ospaths.nim");
	q = ((NI) 1);
	nimln_(257, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_9;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) <= (path ? path->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_9 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_9)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI) 2);
	}
	LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_10;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(258, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_10 = subInt((path ? path->Sup.len : 0), q);
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_10);
		nimln_(1943, "system.nim");
		res = colontmp_;
		{
			nimln_(1944, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_11;
				nimln_(258, "ospaths.nim");
				if (!(((NI) 0) <= res)) goto LA9;
				nimln_(1945, "system.nim");
				i = res;
				nimln_(259, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(92)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA12_;
					result = i;
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(1946, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_11 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_11);
			} LA9: ;
		}
	}
	nimln_(260, "ospaths.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path) {
	NimStringDesc* result;
	NI sepPos;
	nimfr_("parentDir", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(270, "ospaths.nim");
	sepPos = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(path);
	nimln_(271, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_12;
		if (!(((NI) 0) <= sepPos)) goto LA3_;
		nimln_(272, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_12 = subInt(sepPos, ((NI) 1));
		result = copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_12));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(274, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nostailDir)(NimStringDesc* path) {
	NimStringDesc* result;
	NI q;
	nimfr_("tailDir", "ospaths.nim")
{	result = (NimStringDesc*)0;
	nimln_(283, "ospaths.nim");
	q = ((NI) 1);
	nimln_(284, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_13;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) <= (path ? path->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_13 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_13)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI) 2);
	}
	LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_14;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(285, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_14 = subInt((path ? path->Sup.len : 0), q);
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_14);
		nimln_(1955, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1956, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_16;
				if (!(res <= colontmp_)) goto LA9;
				nimln_(1957, "system.nim");
				i = res;
				nimln_(286, "ospaths.nim");
				{
					NI TM_jvWQYw9bcuYhftfPX2ynPeg_15;
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(92)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA12_;
					nimln_(287, "ospaths.nim");
					TM_jvWQYw9bcuYhftfPX2ynPeg_15 = addInt(i, ((NI) 1));
					result = copyStr(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_15));
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(1976, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_16 = addInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_16);
			} LA9: ;
		}
	}
	nimln_(288, "ospaths.nim");
	result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("isRootDir", "ospaths.nim")
	result = (NIM_BOOL)0;
	nimln_(293, "ospaths.nim");
	T1_ = (NI)0;
	T1_ = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(path);
	result = (T1_ < ((NI) 0));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, slashdotdotslash__lXoMhn1ZYc9cAJa9bfA61msg_2)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	NI sepPos;
	nimfr_("/../", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(323, "ospaths.nim");
	sepPos = parentDirPos_GvT9b2csQmLzVANEJ9bdAuNA(head);
	nimln_(324, "ospaths.nim");
	{
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_17;
		NimStringDesc* T5_;
		if (!(((NI) 0) <= sepPos)) goto LA3_;
		nimln_(325, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_17 = subInt(sepPos, ((NI) 1));
		T5_ = (NimStringDesc*)0;
		T5_ = copyStrLast(head, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_17));
		result = slash__lXoMhn1ZYc9cAJa9bfA61msg(T5_, tail);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(327, "ospaths.nim");
		result = slash__lXoMhn1ZYc9cAJa9bfA61msg(head, tail);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, normExt_3yxSdoh5oykvpUqYYeaz2g)(NimStringDesc* ext) {
	NimStringDesc* result;
	nimfr_("normExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(330, "ospaths.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((ext) && (ext)->Sup.len == 0);
		if (T3_) goto LA4_;
		if ((NU)(((NI) 0)) > (NU)(ext->Sup.len)) raiseIndexError();
		T3_ = ((NU8)(ext->data[((NI) 0)]) == (NU8)(46));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = copyString(ext);
	}
	goto LA1_;
	LA5_: ;
	{
		NimStringDesc* T8_;
		nimln_(331, "ospaths.nim");
		T8_ = (NimStringDesc*)0;
		T8_ = rawNewString(ext->Sup.len + 1);
appendChar(T8_, 46);
appendString(T8_, ext);
		result = T8_;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2)(NimStringDesc* path) {
	NI result;
	nimfr_("searchExtPos", "ospaths.nim")
	result = (NI)0;
	nimln_(337, "ospaths.nim");
	result = ((NI) -1);
	{
		NI i;
		NI colontmp_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_18;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(338, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_18 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_18);
		nimln_(1943, "system.nim");
		res = colontmp_;
		{
			nimln_(1944, "system.nim");
			while (1) {
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_19;
				nimln_(338, "ospaths.nim");
				if (!(((NI) 1) <= res)) goto LA3;
				nimln_(1945, "system.nim");
				i = res;
				nimln_(339, "ospaths.nim");
				{
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!((NU8)(path->data[i]) == (NU8)(46))) goto LA6_;
					nimln_(340, "ospaths.nim");
					result = i;
					nimln_(341, "ospaths.nim");
					goto LA1;
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(342, "ospaths.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i])) == ((NU8)(92)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA9_;
					nimln_(343, "ospaths.nim");
					goto LA1;
				}
				goto LA4_;
				LA9_: ;
				LA4_: ;
				nimln_(1946, "system.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_19 = subInt(res, ((NI) 1));
				res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_19);
			} LA3: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY_7q7q3E6Oj24ZNVJb9aonhAg* Result) {
	nimfr_("splitFile", "ospaths.nim")
	nimln_(362, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_20;
		T3_ = (NIM_BOOL)0;
		T3_ = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (T3_) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_20 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_20)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(363, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(path));
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
		unsureAsgnRef((void**) (&(*Result).Field2), copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8)));
	}
	goto LA1_;
	LA5_: ;
	{
		NI sepPos;
		NI dotPos;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_24;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_25;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_26;
		nimln_(365, "ospaths.nim");
		sepPos = ((NI) -1);
		nimln_(366, "ospaths.nim");
		dotPos = (path ? path->Sup.len : 0);
		{
			NI i;
			NI colontmp_;
			NI TM_jvWQYw9bcuYhftfPX2ynPeg_21;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(367, "ospaths.nim");
			TM_jvWQYw9bcuYhftfPX2ynPeg_21 = subInt((path ? path->Sup.len : 0), ((NI) 1));
			colontmp_ = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_21);
			nimln_(1943, "system.nim");
			res = colontmp_;
			{
				nimln_(1944, "system.nim");
				while (1) {
					NI TM_jvWQYw9bcuYhftfPX2ynPeg_23;
					nimln_(367, "ospaths.nim");
					if (!(((NI) 0) <= res)) goto LA10;
					nimln_(1945, "system.nim");
					i = res;
					nimln_(368, "ospaths.nim");
					{
						if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[i]) == (NU8)(46))) goto LA13_;
						nimln_(369, "ospaths.nim");
						{
							NIM_BOOL T17_;
							NIM_BOOL T18_;
							NI TM_jvWQYw9bcuYhftfPX2ynPeg_22;
							T17_ = (NIM_BOOL)0;
							T18_ = (NIM_BOOL)0;
							T18_ = (dotPos == (path ? path->Sup.len : 0));
							if (!(T18_)) goto LA19_;
							T18_ = (((NI) 0) < i);
							LA19_: ;
							T17_ = T18_;
							if (!(T17_)) goto LA20_;
							nimln_(1154, "system.nim");
							nimln_(370, "ospaths.nim");
							TM_jvWQYw9bcuYhftfPX2ynPeg_22 = subInt(i, ((NI) 1));
							if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)) > (NU)(path->Sup.len)) raiseIndexError();
							T17_ = !((((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_22)])) == ((NU8)(47))));
							LA20_: ;
							if (!T17_) goto LA21_;
							dotPos = i;
						}
						LA21_: ;
					}
					goto LA11_;
					LA13_: ;
					{
						nimln_(371, "ospaths.nim");
						if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
						if (!(((NU8)(path->data[i])) == ((NU8)(92)) || ((NU8)(path->data[i])) == ((NU8)(47)))) goto LA24_;
						nimln_(372, "ospaths.nim");
						sepPos = i;
						nimln_(373, "ospaths.nim");
						goto LA8;
					}
					goto LA11_;
					LA24_: ;
					LA11_: ;
					nimln_(1946, "system.nim");
					TM_jvWQYw9bcuYhftfPX2ynPeg_23 = subInt(res, ((NI) 1));
					res = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_23);
				} LA10: ;
			}
		} LA8: ;
		nimln_(374, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_24 = subInt(sepPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_24)));
		nimln_(375, "ospaths.nim");
		TM_jvWQYw9bcuYhftfPX2ynPeg_25 = addInt(sepPos, ((NI) 1));
		TM_jvWQYw9bcuYhftfPX2ynPeg_26 = subInt(dotPos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStrLast(path, (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_25), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_26)));
		nimln_(376, "ospaths.nim");
		unsureAsgnRef((void**) (&(*Result).Field2), copyStr(path, dotPos));
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path) {
	NimStringDesc* result;
	nimfr_("extractFilename", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(382, "ospaths.nim");
	{
		NIM_BOOL T3_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_27;
		T3_ = (NIM_BOOL)0;
		T3_ = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (T3_) goto LA4_;
		TM_jvWQYw9bcuYhftfPX2ynPeg_27 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)) > (NU)(path->Sup.len)) raiseIndexError();
		T3_ = (((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_27)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(383, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
	}
	goto LA1_;
	LA5_: ;
	{
		TY_UV3llMMYFckfui8YMBuUZA T8_;
		nimln_(385, "ospaths.nim");
		memset((void*)(&T8_), 0, sizeof(T8_));
		nossplitPath(path, (&T8_));
		result = copyString(T8_.Field1);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extPos;
	nimfr_("changeFileExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(397, "ospaths.nim");
	extPos = searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2(filename);
	nimln_(398, "ospaths.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		if (!(extPos < ((NI) 0))) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T5_ = rawNewString(filename->Sup.len + T6_->Sup.len + 0);
appendString(T5_, filename);
appendString(T5_, T6_);
		result = T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T8_;
		NI TM_jvWQYw9bcuYhftfPX2ynPeg_28;
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		nimln_(399, "ospaths.nim");
		T8_ = (NimStringDesc*)0;
		TM_jvWQYw9bcuYhftfPX2ynPeg_28 = subInt(extPos, ((NI) 1));
		T9_ = (NimStringDesc*)0;
		T9_ = copyStrLast(filename, ((NI) 0), (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_28));
		T10_ = (NimStringDesc*)0;
		T10_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T8_ = rawNewString(T9_->Sup.len + T10_->Sup.len + 0);
appendString(T8_, T9_);
appendString(T8_, T10_);
		result = T8_;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extPos;
	nimfr_("addFileExt", "ospaths.nim")
	result = (NimStringDesc*)0;
	nimln_(409, "ospaths.nim");
	extPos = searchExtPos_GvT9b2csQmLzVANEJ9bdAuNA_2(filename);
	nimln_(410, "ospaths.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		if (!(extPos < ((NI) 0))) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = normExt_3yxSdoh5oykvpUqYYeaz2g(ext);
		T5_ = rawNewString(filename->Sup.len + T6_->Sup.len + 0);
appendString(T5_, filename);
appendString(T5_, T6_);
		result = T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(411, "ospaths.nim");
		result = copyString(filename);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, noscmpPaths)(NimStringDesc* pathA, NimStringDesc* pathB) {
	NI result;
	nimfr_("cmpPaths", "ospaths.nim")
	result = (NI)0;
	nimln_(423, "ospaths.nim");
	{
		if (!NIM_FALSE) goto LA3_;
		nimln_(424, "ospaths.nim");
		result = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(pathA, pathB);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(430, "ospaths.nim");
		result = nsuCmpIgnoreCase(pathA, pathB);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path) {
	NIM_BOOL result;
	NI len;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T5_;
	NIM_BOOL T6_;
	nimfr_("isAbsolute", "ospaths.nim")
	result = (NIM_BOOL)0;
	nimln_(437, "ospaths.nim");
	len = (path ? path->Sup.len : 0);
	nimln_(438, "ospaths.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T2_ = (((NI) 0) < len);
	if (!(T2_)) goto LA3_;
	if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
	T2_ = (((NU8)(path->data[((NI) 0)])) == ((NU8)(47)) || ((NU8)(path->data[((NI) 0)])) == ((NU8)(92)));
	LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA4_;
	nimln_(439, "ospaths.nim");
	T5_ = (NIM_BOOL)0;
	T6_ = (NIM_BOOL)0;
	T6_ = (((NI) 1) < len);
	if (!(T6_)) goto LA7_;
	if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
	T6_ = (((NU8)(path->data[((NI) 0)])) >= ((NU8)(97)) && ((NU8)(path->data[((NI) 0)])) <= ((NU8)(122)) || ((NU8)(path->data[((NI) 0)])) >= ((NU8)(65)) && ((NU8)(path->data[((NI) 0)])) <= ((NU8)(90)));
	LA7_: ;
	T5_ = T6_;
	if (!(T5_)) goto LA8_;
	if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
	T5_ = ((NU8)(path->data[((NI) 1)]) == (NU8)(58));
	LA8_: ;
	T1_ = T5_;
	LA4_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path, NimStringDesc* drive) {
	NimStringDesc* result;
	NI start;
	NI i;
	nimfr_("unixToNativePath", "ospaths.nim")
	result = (NimStringDesc*)0;
	start = (NI)0;
	nimln_(463, "ospaths.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
		if (!((NU8)(path->data[((NI) 0)]) == (NU8)(47))) goto LA3_;
		nimln_(466, "ospaths.nim");
		{
			NimStringDesc* T9_;
			nimln_(363, "system.nim");
			nimln_(466, "ospaths.nim");
			if (!!(((drive) && (drive)->Sup.len == 0))) goto LA7_;
			nimln_(467, "ospaths.nim");
			T9_ = (NimStringDesc*)0;
			T9_ = rawNewString(drive->Sup.len + 2);
appendString(T9_, drive);
appendString(T9_, ((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_29));
			result = T9_;
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(469, "ospaths.nim");
			result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_30));
		}
		LA5_: ;
		nimln_(474, "ospaths.nim");
		start = ((NI) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T12_;
		nimln_(475, "ospaths.nim");
		T12_ = (NIM_BOOL)0;
		if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
		T12_ = ((NU8)(path->data[((NI) 0)]) == (NU8)(46));
		if (!(T12_)) goto LA13_;
		if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
		T12_ = ((NU8)(path->data[((NI) 1)]) == (NU8)(47));
		LA13_: ;
		if (!T12_) goto LA14_;
		nimln_(477, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_31));
		nimln_(478, "ospaths.nim");
		start = ((NI) 2);
	}
	goto LA1_;
	LA14_: ;
	{
		nimln_(480, "ospaths.nim");
		result = copyString(((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_8));
		nimln_(481, "ospaths.nim");
		start = ((NI) 0);
	}
	LA1_: ;
	nimln_(483, "ospaths.nim");
	i = start;
	{
		nimln_(484, "ospaths.nim");
		while (1) {
			if (!(i < (path ? path->Sup.len : 0))) goto LA18;
			nimln_(485, "ospaths.nim");
			{
				NIM_BOOL T21_;
				NIM_BOOL T22_;
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_32;
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_33;
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_35;
				T21_ = (NIM_BOOL)0;
				T22_ = (NIM_BOOL)0;
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				T22_ = ((NU8)(path->data[i]) == (NU8)(46));
				if (!(T22_)) goto LA23_;
				TM_jvWQYw9bcuYhftfPX2ynPeg_32 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_32)) > (NU)(path->Sup.len)) raiseIndexError();
				T22_ = ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_32)]) == (NU8)(46));
				LA23_: ;
				T21_ = T22_;
				if (!(T21_)) goto LA24_;
				TM_jvWQYw9bcuYhftfPX2ynPeg_33 = addInt(i, ((NI) 2));
				if ((NU)((NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_33)) > (NU)(path->Sup.len)) raiseIndexError();
				T21_ = ((NU8)(path->data[(NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_33)]) == (NU8)(47));
				LA24_: ;
				if (!T21_) goto LA25_;
				nimln_(493, "ospaths.nim");
				result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM_jvWQYw9bcuYhftfPX2ynPeg_34));
				nimln_(494, "ospaths.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_35 = addInt(i, ((NI) 3));
				i = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_35);
			}
			goto LA19_;
			LA25_: ;
			{
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_36;
				nimln_(495, "ospaths.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				if (!((NU8)(path->data[i]) == (NU8)(47))) goto LA28_;
				nimln_(496, "ospaths.nim");
				result = addChar(result, 92);
				nimln_(497, "ospaths.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_36 = addInt(i, ((NI) 1));
				i = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_36);
			}
			goto LA19_;
			LA28_: ;
			{
				NI TM_jvWQYw9bcuYhftfPX2ynPeg_37;
				nimln_(499, "ospaths.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				result = addChar(result, path->data[i]);
				nimln_(500, "ospaths.nim");
				TM_jvWQYw9bcuYhftfPX2ynPeg_37 = addInt(i, ((NI) 1));
				i = (NI)(TM_jvWQYw9bcuYhftfPX2ynPeg_37);
			}
			LA19_: ;
		} LA18: ;
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void) {
	nimfr_("ospaths", "ospaths.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void) {
}

