/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\ZACH\Documents\mingw64\bin\gcc.exe -c  -w  -IC:\Users\ZACH\Documents\nim-0.17.0\lib -o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_locks.o C:\Users\ZACH\Documents\nim\chapter3\chatapp\src\nimcache\stdlib_locks.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI, TY_KeCiSdV9aG0JRdXpLIxCQ9cQ) (void* lpEventAttributes, NI32 bManualReset, NI32 bInitialState, NCSTRING lpName);
typedef N_STDCALL_PTR(void, TY_ofoySXaAAlxxs9bQS9a1etlg) (NI hObject);
typedef N_STDCALL_PTR(NI32, TY_FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle, NI32 dwMilliseconds);
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NIM_BOOL, tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks)(CRITICAL_SECTION* L);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, initSysCond_05dikp5SjY49b5qLvlucEZglocks)(NI* cond);
static N_INLINE(void, deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks)(NI* cond);
N_NIMCALL(void, waitSysCond_m9bKYHzrEzSKf0WFiiK5huw)(NI* cond, CRITICAL_SECTION* lock);
N_NIMCALL(void, waitSysCondWindows_FIpIuhuN2u8V5BcL9cF69aWA)(NI* cond);
static N_INLINE(void, initLock_NXoRcxfV39aV9cflSTUwtJ1glocks)(CRITICAL_SECTION* lock);
static N_INLINE(void, deinitLock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(CRITICAL_SECTION* lock);
N_NIMCALL(NIM_BOOL, tryAcquire_RVpMCi0dWU5mH1GyAP2R5w)(CRITICAL_SECTION* lock);
N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(CRITICAL_SECTION* lock);
N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(CRITICAL_SECTION* lock);
static N_INLINE(void, initCond_05dikp5SjY49b5qLvlucEZg_3locks)(NI* cond);
static N_INLINE(void, deinitCond_05dikp5SjY49b5qLvlucEZg_4locks)(NI* cond);
static N_INLINE(void, wait_Lc8rxHP8fVJMsOe9cdzwpuAlocks)(NI* cond, CRITICAL_SECTION* lock);
static N_INLINE(void, signal_05dikp5SjY49b5qLvlucEZg_5locks)(NI* cond);
static void* TM_05xOtLU9bCAYnon4m09bcBlg_2;
TY_KeCiSdV9aG0JRdXpLIxCQ9cQ Dl_62244_;
TY_ofoySXaAAlxxs9bQS9a1etlg Dl_62250_;
TY_FprzxJFfqQdWyyGxiUsmeQ Dl_62253_;
TY_ofoySXaAAlxxs9bQS9a1etlg Dl_62257_;
TNimType NTI_lsB6JckQ3csMuiRW476VWg_;
STRING_LITERAL(TM_05xOtLU9bCAYnon4m09bcBlg_4, "kernel32", 8);
STRING_LITERAL(TM_05xOtLU9bCAYnon4m09bcBlg_5, "kernel32", 8);

static N_INLINE(NIM_BOOL, tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks)(CRITICAL_SECTION* L) {
	NIM_BOOL result;
	NI32 T1_;
	result = (NIM_BOOL)0;
	T1_ = (NI32)0;
	T1_ = TryEnterCriticalSection(L);
	result = !((T1_ == ((NI32) 0)));
	return result;
}

static N_INLINE(void, initSysCond_05dikp5SjY49b5qLvlucEZglocks)(NI* cond) {
	(*cond) = Dl_62244_(NIM_NIL, ((NI32) 0), ((NI32) 0), NIM_NIL);
}

static N_INLINE(void, deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks)(NI* cond) {
	Dl_62250_((*cond));
}

N_NIMCALL(void, waitSysCond_m9bKYHzrEzSKf0WFiiK5huw)(NI* cond, CRITICAL_SECTION* lock) {
	NI32 T1_;
	LeaveCriticalSection(lock);
	T1_ = (NI32)0;
	T1_ = Dl_62253_((*cond), ((NI32) -1));
	EnterCriticalSection(lock);
}

N_NIMCALL(void, waitSysCondWindows_FIpIuhuN2u8V5BcL9cF69aWA)(NI* cond) {
	NI32 T1_;
	T1_ = (NI32)0;
	T1_ = Dl_62253_((*cond), ((NI32) -1));
}

static N_INLINE(void, initLock_NXoRcxfV39aV9cflSTUwtJ1glocks)(CRITICAL_SECTION* lock) {
	InitializeCriticalSection(lock);
}

static N_INLINE(void, deinitLock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(CRITICAL_SECTION* lock) {
	DeleteCriticalSection(lock);
}

N_NIMCALL(NIM_BOOL, tryAcquire_RVpMCi0dWU5mH1GyAP2R5w)(CRITICAL_SECTION* lock) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = tryAcquireSys_1IhqNgQW3p2BHbc9bb4WjNAlocks(lock);
	return result;
}

N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(CRITICAL_SECTION* lock) {
	EnterCriticalSection(lock);
}

N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(CRITICAL_SECTION* lock) {
	LeaveCriticalSection(lock);
}

static N_INLINE(void, initCond_05dikp5SjY49b5qLvlucEZg_3locks)(NI* cond) {
	initSysCond_05dikp5SjY49b5qLvlucEZglocks(cond);
}

static N_INLINE(void, deinitCond_05dikp5SjY49b5qLvlucEZg_4locks)(NI* cond) {
	deinitSysCond_05dikp5SjY49b5qLvlucEZg_2locks(cond);
}

static N_INLINE(void, wait_Lc8rxHP8fVJMsOe9cdzwpuAlocks)(NI* cond, CRITICAL_SECTION* lock) {
	waitSysCond_m9bKYHzrEzSKf0WFiiK5huw(cond, lock);
}

static N_INLINE(void, signal_05dikp5SjY49b5qLvlucEZg_5locks)(NI* cond) {
	Dl_62257_((*cond));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void) {
static TNimNode TM_05xOtLU9bCAYnon4m09bcBlg_0[1];
NTI_lsB6JckQ3csMuiRW476VWg_.size = sizeof(CRITICAL_SECTION);
NTI_lsB6JckQ3csMuiRW476VWg_.kind = 18;
NTI_lsB6JckQ3csMuiRW476VWg_.base = 0;
NTI_lsB6JckQ3csMuiRW476VWg_.flags = 3;
NTI_lsB6JckQ3csMuiRW476VWg_.node = &TM_05xOtLU9bCAYnon4m09bcBlg_0[0];
if (!((TM_05xOtLU9bCAYnon4m09bcBlg_2 = nimLoadLibrary((NimStringDesc*) &TM_05xOtLU9bCAYnon4m09bcBlg_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_05xOtLU9bCAYnon4m09bcBlg_5);
	Dl_62244_ = (TY_KeCiSdV9aG0JRdXpLIxCQ9cQ) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "CreateEventA");
	Dl_62250_ = (TY_ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "CloseHandle");
	Dl_62253_ = (TY_FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "WaitForSingleObject");
	Dl_62257_ = (TY_ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM_05xOtLU9bCAYnon4m09bcBlg_2, "SetEvent");
}

